name: Build
on:
  push:
    tags:
      - '*'

env:
  NORTHSTAR_VERSION: ${{ github.ref_name }}

jobs:
  build-launcher:
    runs-on: windows-2022
    steps:
      - name: Setup bundled plugins
        uses: actions/checkout@v2
        with:
          repository: R2Northstar/NorthstarDiscordRPC
          path: discord-plugin
      - name: Checkout launcher repository
        uses: actions/checkout@v2
        with:
          repository: R2Northstar/NorthstarLauncher
          ref: ${{ env.NORTHSTAR_VERSION }}
          path: northstar-launcher
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup resource file version
        shell: bash
        working-directory: northstar-launcher
        run: |
          sed -i 's/DEV/${{ env.NORTHSTAR_VERSION }}/g' LauncherInjector/resources.rc
          FILEVERSION=$(echo ${{ env.NORTHSTAR_VERSION }} | tr '.' ',' | tr -d '[:alpha:]')
          sed -i "s/0,0,0,1/${FILEVERSION}/g" LauncherInjector/resources.rc
      - name: Build
        working-directory: northstar-launcher 
        run: |
          cp -r ../discord-plugin/*Discord* .
          msbuild /p:Configuration=Release R2Northstar.sln
          msbuild /p:Configuration=Release NorthstarDiscordRPC.sln
      - name: Upload launcher build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: northstar-launcher
          path: |
            northstar-launcher/x64/Release/Northstar.dll
            northstar-launcher/x64/Release/wsock32.dll
            northstar-launcher/x64/Release/NorthstarLauncher.exe
            northstar-launcher/x64/Release/discord_game_sdk.dll
            northstar-launcher/x64/Release/DiscordRPC.dll
            northstar-launcher/x64/Release/*.txt
      - name: Upload debug build artifact
        uses: actions/upload-artifact@v2
        with:
          name: launcher-debug-files
          path: |
            northstar-launcher/x64/Release/*.pdb

  build-northstar:
    needs: build-launcher
    runs-on: ubuntu-20.04
    steps:
      - name: Download compiled launcher
        uses: actions/download-artifact@v2
        with:
          name: northstar-launcher
          path: northstar-launcher
      - name: Download compiled stubs
        run:
          wget "https://github.com/R2Northstar/NorthstarStubs/releases/download/v1/NorthstarStubs.zip"
      - name: Checkout release files
        uses: actions/checkout@v2
        with:
          ref: ${{ env.NORTHSTAR_VERSION }}
          path: northstar
      - name: Checkout core mods
        uses: actions/checkout@v2
        with:
          repository: R2Northstar/NorthstarMods
          ref: ${{ env.NORTHSTAR_VERSION }}
          path: northstar-mods
      - name: Update mod version info
        run: |
          export MOD_VERSION=$(echo $NORTHSTAR_VERSION | tr -d 'v')
          cat <<< $(jq ".Version = \"${MOD_VERSION}\"" northstar-mods/Northstar.Client/mod.json) > northstar-mods/Northstar.Client/mod.json
          cat <<< $(jq ".Version = \"${MOD_VERSION}\"" northstar-mods/Northstar.Custom/mod.json) > northstar-mods/Northstar.Custom/mod.json
          cat <<< $(jq ".Version = \"${MOD_VERSION}\"" northstar-mods/Northstar.CustomServers/mod.json) > northstar-mods/Northstar.CustomServers/mod.json
      - name: Generate md5sum file
        working-directory: northstar-mods
        run: |
          echo -e "# Check with 'md5sum -c md5sum.txt' at the root of mods folder\n" > md5sum.txt
          git ls-tree -r $NORTHSTAR_VERSION --name-only | xargs -L1 md5sum >> md5sum.txt
      - name: Make folder structure
        run: |
          mv -v northstar/release/* northstar/.
          mkdir -p northstar/R2Northstar/mods
          mkdir -p northstar/R2Northstar/plugins
          mkdir -p northstar/bin/x64_retail
          mv -v northstar-launcher/DiscordRPC.dll northstar/R2Northstar/plugins
          mv -v northstar-launcher/discord_game_sdk.dll northstar
          mv -v northstar-launcher/wsock32.dll northstar/bin/x64_retail
          unzip NorthstarStubs.zip -d northstar/bin/x64_dedi
          mv -v northstar-launcher/* northstar
          rsync -avr --exclude="Northstar.Coop" --exclude=".git*" northstar-mods/. northstar/R2Northstar/mods
      - name: Cleanup
        run: |
          rm -rf northstar-launcher
          cd northstar && rm -rf .git .github *.md LICENSE
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Northstar.release.${{ env.NORTHSTAR_VERSION }}
          path: northstar
